# -*- coding: utf-8 -*-
"""Introduction-to-Data-Science-with-Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KkHRNRvhQoaa_pHibGmTP1zuqujk0aIM

# **[Python "Hello World" & Statement](https://academy.dqlab.id/main/livecode/162/306/1398)**
"""

print("Hello World.")
print("Saya Aksara, baru belajar Python.")

"""# **[Variables di Python](https://academy.dqlab.id/main/livecode/162/306/1399)**"""

bil1 = 10
bil_2 = 20
Frasa = "Halo Dunia"
bil1, bil_2 = 10, 20
salam = "Selamat Pagi"; Penutup = "Salam Sejahtera"

"""# **[Comments di Python](https://academy.dqlab.id/main/livecode/162/306/1401)**"""

# perintah pada baris ini tidak mempengaruhi program
'''
perintah ini tidak akan dieksekusi oleh Python
dan perintah ini juga tidak akan dieksekusi
perintah ini juga tidak akan dieksekusi
'''
print("jadi # digunakan untuk membuat comment pada Python")

"""# **[Tugas Praktek](https://academy.dqlab.id/main/livecode/162/307/1406)**"""

text = "Belajar Python di DQLab."
print(list(text))
print(tuple(text))
print(set(text))

"""# **[Menggunakan Library di Python](https://academy.dqlab.id/main/livecode/162/307/1408)**"""

import math
import numpy as np
import pandas as pd
import seaborn as sns